accounts/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.show_login, name='login'),
    path('logout/', views.show_logout, name='logout'),
    path('myprofile/', views.show_my_profile, name='myprofile'),
]

entities/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import models_views
from . import views

app_name = 'entities'

urlpatterns = [
    path('timetables/student', views.show_student_plans, name='timetables_student'),
    path('timetables/teacher', views.show_teachers_plans, name='timetables_teacher'),
    path('timetables/room', views.show_rooms_plans, name='timetables_room'),
    path('edittimetables', views.show_edit_timetable, name='edittimetables'),
    path('studentplans/', views.show_choose_plan, name='studentplans'),
    path('studentplan/', views.show_student_plan, name="studentplan"),
    path('teacherplan/', views.show_teacher_plan, name='teacherplan'),
    path('generate/', views.show_generate_page, name='generate'),
    path('forbidden/', views.show_forbidden, name='forbidden'),
]

tab_models_urls = [
    path('admin/models/', models_views.show_intro_edit_models, name='models'),
    path('admin/models/building', models_views.show_building, name='model_building'),
    path('admin/models/faculty', models_views.show_faculty, name='model_faculty'),
    path('admin/models/fieldofstudy', models_views.show_fieldofstudy, name='model_field_of_study'),
    path('admin/models/plan', models_views.show_plan, name='model_plan'),
    path('admin/models/room', models_views.show_room, name='model_room'),
    path('admin/models/scheduledsubject', models_views.show_scheduledsubject, name='model_scheduledsubject'),
    path('admin/models/subject', models_views.show_subject, name='model_subject'),
    path('admin/models/student', models_views.show_student, name='model_student'),
    path('admin/models/teacher', models_views.show_teacher, name='model_teacher'),
    path('admin/models/user', models_views.show_user, name='model_user'),
    path('admin/models/teacher_to_subject', models_views.show_teacher_to_subject, name="model_teachertosubject")
]

urlpatterns += tab_models_urls

mainproject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.show_about),
    path('entities/', include('entities.urls')),
    path('accounts/', include('accounts.urls')),
    re_path('^$', views.show_index, name='homepage'),
]

urlpatterns += staticfiles_urlpatterns()

templates/about.html
{% extends 'base_layout.html' %}
{% block title %}
<title> About us </title>
{% endblock %}
{% block content %}
<div>
    <p> App was created by Adam </p>
</div>
{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title> My account </title>
    {% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="{% static 'bootstrap-4.1.3/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'myownstyles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark background-first mb-4">
            <a href="/" class="navbar-brand"> UniversityMainPage </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <div class="dropdown ">
                        <button class="btn dropdown-toggle background-first" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        All Plans
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                            <form action="{% url 'entities:timetables_student' %}" method="get">
                                <button class="dropdown-item" type="submit"> Students </button>
                            </form>
                            <form action="{% url 'entities:timetables_teacher' %}" method="get">
                                <button class="dropdown-item" type="submit"> Teachers </button>
                            </form>
                            <form action="{% url 'entities:timetables_room' %}" method="get">
                                <button class="dropdown-item" type="submit"> Rooms </button>
                            </form>
                        </div>
                    </div>
                    <!--
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entities:generate' %}"> Generate plans </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entities:edittimetables' %}"> Edit plans </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entities:studentplans' %}"> Choose plan </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entities:studentplan' %}"> My plan s </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entities:teacherplan' %}"> My plan t </a>
                    </li>
                    -->
                    {% if user.is_authenticated %}
                        {% if user.admin %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'entities:generate' %}"> Generate plans </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'entities:edittimetables' %}"> Edit plans </a>
                            </li>
                            <div class="dropdown ">
                                <button class="btn dropdown-toggle background-first" type="button" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin functions
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                    <form action="{% url 'entities:model_student' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Students </button>
                                    </form>
                                    <form action="{% url 'entities:model_teacher' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Teachers </button>
                                    </form>
                                    <form action="{% url 'entities:model_user' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Admins </button>
                                    </form>
                                    <div class="dropdown-divider"></div>
                                    <form action="{% url 'entities:model_building' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Buildings </button>
                                    </form>
                                    <form action="{% url 'entities:model_faculty' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Faculties </button>
                                    </form>
                                    <form action="{% url 'entities:model_field_of_study' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Fields of study </button>
                                    </form>
                                    <form action="{% url 'entities:model_plan' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Plans </button>
                                    </form>
                                    <form action="{% url 'entities:model_room' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Rooms </button>
                                    </form>
                                    <form action="{% url 'entities:model_scheduledsubject' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Scheduled subjects </button>
                                    </form>
                                    <form action="{% url 'entities:model_subject' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Subjects </button>
                                    </form>
                                    </div>
                                </div>
                        {% endif %}
                        {% if user.student %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'entities:studentplans' %}"> Choose plan </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'entities:studentplan' %}"> My plan </a>
                            </li>
                        {% endif %}
                        {% if user.teacher %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'entities:teacherplan' %}"> My plan </a>
                            </li>
                        {% endif %}
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="/about"> About us </a>
                    </li>
                </ul>
                <div class="form-inline mt-2 mt-md-0">
                    {% if user.is_authenticated %}
                        <form action="{% url 'accounts:myprofile' %}" method="get">
                            <button class="nav-item btn background-second button-margin" type="submit">
                                My account: {{ user.username }}
                            </button>
                        </form>
                        <form action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button class="nav-item btn background-second button-margin" type="submit">
                                Logout
                            </button>
                        </form>
                    {% else %}
                        <form action="{% url 'accounts:login' %}" method="GET">
                            {% csrf_token %}
                            <button class="nav-item btn background-second" type="submit">
                                Login
                            </button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </nav>
        <div class="container background-third full-height">
        {% block content %}
        {% endblock %}
        </div>
</body>
</html>

templates/base_layout_timetable.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title> My account </title>
    {% endblock %}
    <!-- <script src="{% static 'jquery-3.3.1.min.js' %}"></script> -->
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'myownstyles.css' %}"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="{% static 'bootstrap-4.1.3\js\bootstrap.min.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark background-first mb-4">
            <a href="/" class="navbar-brand"> UniversityMainPage </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <div class="dropdown">
                        <button class="btn dropdown-toggle background-first" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        All Plans
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                            <form action="{% url 'entities:timetables_student' %}" method="get">
                                <button class="dropdown-item" type="submit"> Students </button>
                            </form>
                            <form action="{% url 'entities:timetables_teacher' %}" method="get">
                                <button class="dropdown-item" type="submit"> Teachers </button>
                            </form>
                            <form action="{% url 'entities:timetables_room' %}" method="get">
                                <button class="dropdown-item" type="submit"> Rooms </button>
                            </form>
                        </div>
                    </div>
                    <!--
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entities:generate' %}"> Generate plans </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entities:edittimetables' %}"> Edit plans </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entities:studentplans' %}"> Choose plan </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entities:studentplan' %}"> My plan s </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entities:teacherplan' %}"> My plan t </a>
                    </li>
                    -->
                    {% if user.is_authenticated %}
                        {% if user.admin %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'entities:generate' %}"> Generate plans </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'entities:edittimetables' %}"> Edit plans </a>
                            </li>
                            <div class="dropdown ">
                                <button class="btn dropdown-toggle background-first" type="button" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin functions
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                    <form action="{% url 'entities:model_student' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Students </button>
                                    </form>
                                    <form action="{% url 'entities:model_teacher' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Teachers </button>
                                    </form>
                                    <form action="{% url 'entities:model_user' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Admins </button>
                                    </form>
                                    <div class="dropdown-divider"></div>
                                    <form action="{% url 'entities:model_building' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Buildings </button>
                                    </form>
                                    <form action="{% url 'entities:model_faculty' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Faculties </button>
                                    </form>
                                    <form action="{% url 'entities:model_field_of_study' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Fields of study </button>
                                    </form>
                                    <form action="{% url 'entities:model_plan' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Plans </button>
                                    </form>
                                    <form action="{% url 'entities:model_room' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Rooms </button>
                                    </form>
                                    <form action="{% url 'entities:model_scheduledsubject' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Scheduled subjects </button>
                                    </form>
                                    <form action="{% url 'entities:model_subject' %}" method="get">
                                        <button class="dropdown-item" type="submit"> Subjects </button>
                                    </form>
                                </div>
                            </div>
                        {% endif %}
                        {% if user.student %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'entities:studentplans' %}"> Choose plan </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'entities:studentplan' %}"> My plan </a>
                            </li>
                        {% endif %}
                        {% if user.teacher %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'entities:teacherplan' %}"> My plan </a>
                            </li>
                        {% endif %}
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="/about"> About us </a>
                    </li>
                </ul>
                <div class="form-inline mt-2 mt-md-0">
                    {% if user.is_authenticated %}
                        <form action="{% url 'accounts:myprofile' %}" method="get">
                            <button class="nav-item btn background-second button-margin" type="submit">
                                My account: {{ user.username }}
                            </button>
                        </form>
                        <form action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button class="nav-item btn background-second button-margin" type="submit">
                                Logout
                            </button>
                        </form>
                    {% else %}
                        <form action="{% url 'accounts:login' %}" method="GET">
                            {% csrf_token %}
                            <button class="nav-item btn background-second" type="submit">
                                Login
                            </button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </nav>
        <div class="container background-third full-height">
        {% block content %}
        {% endblock %}
        </div>
</body>
</html>

templates/index.html
{% extends 'base_layout.html' %}
{% block title %}
<title> Homepage </title>
{% endblock %}
{% block content %}
<div>
    <h1> Home page, welcome! </h1>
</div>
{% endblock %}

templates/main_css_js.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<script src="{% static 'jquery-3.3.1.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="{% static 'bootstrap-4.1.3/js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'styles.css' %}">
<link rel="stylesheet" href="{% static 'myownstyles.css' %}">